version: "2.3"

services:
  main:
    build:
      context: .
      args:
        MODE: dev
    volumes:
      - ./src/:/go/src/
      - ./static/:/go/src/static/
      - ./pages/:/go/src/pages/
      - ./start.sh:/go/src/start.sh
    depends_on:
      - db
    dns: 8.8.8.8
    env_file:
      - .env
    working_dir: /go/src

  db:
    image: postgres:11
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
